import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import "./styles/Initial.css";
import "./styles/skils.css"
import "./styles/about.css"
import "./styles/PageForms.css"
import "./components/Forms/Forms.css"
import "./components/Anchor/Anchor.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
